---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-github-release
spec:
  params:
    - name: githubSecret
      value: ""
    - name: repository
      value: "foo/bar"
    - name: release_version
      value: 1.2.3
  taskRef:
    resolver: "git"
    params:
      # - name: url
      #   value: https://github.com/redhat-appstudio/release-service-bundles.git
      # - name: revision
      #   value: main
      - name: url
        value: https://github.com/ralphbean/release-service-bundles.git
      - name: revision
        value: github-release
      - name: pathInRepo
        value: catalog/task/create-github-release/0.1/create-github-release.yaml
